### ISSUE TITLE
Modal.open(options) ,参数header，content中不能ref索引

### ISSUE THREAD

**Issue by ingf** [Lobos/react-ui#10]
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

**Comment by Lobos** [comment]
这个问题一直没找到是哪的问题，所以一直想等遇到的时候再处理的，一直拖到现在，也一直没发现问题……试试看最新版是否还有这个问题呢？

**Comment by qiuling2014** [comment]
是呀，我也遇到了这个问题，怎么解决呀

**Comment by Lobos** [comment]
一直都没遇到这个问题...
试试看用 ref={(c)=>this._xxxx = c;} 这种ref的方式引用呢。

**Comment by Lobos** [comment]
发了0.6.1，Modal重写了，[文档 ](http://lobos.github.io/react-ui/0.6/#/modal)
