### ISSUE TITLE
请问下用antd表格columns的fixed 用‘left’和’right‘ 错怎么解决？

### ISSUE THREAD

**Issue by ng-work** [Lobos/react-ui#107]
[ts]
Type '{ pagination: { total: number; pageSize: number; defaultPageSize: number; showSizeChanger: true; ...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Table<{}>> & Readonly<{ children?: ReactNode; }> &...'.
  Type '{ pagination: { total: number; pageSize: number; defaultPageSize: number; showSizeChanger: true; ...' is not assignable to type 'Readonly<TableProps<{}>>'.
    Types of property 'columns' are incompatible.
      Type '({ title: string; dataIndex: string; key: string; fixed: boolean; width: number; } | { title: str...' is not assignable to type 'ColumnProps<{}>[]'.
        Type '{ title: string; dataIndex: string; key: string; fixed: boolean; width: number; } | { title: stri...' is not assignable to type 'ColumnProps<{}>'.
          Type '{ title: string; dataindex: string; fixed: string; key: string; width: number; render: (text: any...' is not assignable to type 'ColumnProps<{}>'.
            Types of property 'fixed' are incompatible.
               Type 'string' is not assignable to type 'boolean | "left" | "right"'.
(property) pageSize: number

**Comment by Lobos** [comment]
antd？呃，貌似问错地方了……
