### ISSUE TITLE
关于css modules的问题

### ISSUE THREAD

**Issue by IhInspiration** [Lobos/react-ui#108]
感谢作者的rctui，我有一个问题：

**问题**：我经过配置webpack，最后也编译了rctui，目前css modules部分已经编译好，但是此时所有的css都扔到了html里边，我现在想把css提取出来，有没有什么办法吗？

**我的诉求**：提取之后，加完样式，可以将自己的link放在最后，这样有一些细微样式调整可以自己搞定，否则，我自己link的css无法覆盖rctui的样式，这个目前可以搞吗？

**Comment by IhInspiration** [comment]
你好，我再问个问题，如下两种方式引入表现不一致有解决办法吗

// 方法1
import {Datepicker, Button} from 'rctui';
// 方法2
import Datepicker from 'rctui/Datepicker';
import Button from 'rctui/Button';

和Datepicker一样，FormControl的表现不一致的情况更明显，另外，官方文档的FormControl我这一直打不开，不知道是不是我这的个例

**Comment by Lobos** [comment]
真是抱歉啊，过年前一直在忙，没看到这个issue。这个问题，用localIdentName=[name]-[local]，不要带hash，这样就会生成固定的类名，要修改的话，在自己的文件夹下面建一个相同名称的文件，就可以覆盖样式了。
```
// 方法1
import {Datepicker} from 'rctui';
// 方法2
import Datepicker from 'rctui/Datepicker';
```
这两个表现不一致？是指样式不一致么，**import {Datepicker} from 'rctui'** 会引用 './styles/reset.scss' 这个文件，单独使用组件的时候在入口引用一下这个文件就好了
```
import 'rctui/styles/reset.scss';
```

**Comment by Lobos** [comment]
文档的问题，是有个bug，已经修复。

**Comment by IhInspiration** [comment]
那个表现不一致是这个意思。

比如FormControl的type为date的时候，仅使用import FormControl from 'rctui/FormControl';无法显示，需要再次引入datepicker。是不是和内部组件的注册(formitem.register)有关

**Comment by Lobos** [comment]
是的，import FormControl from 'rctui/FormControl'，是没有引入过DatePicker的，需要在某个地方import一次DatePicker。

**Comment by IhInspiration** [comment]
谢谢
