### ISSUE TITLE
table中pagination中的onChange问题

### ISSUE THREAD

**Issue by zhangqhzz** [Lobos/react-ui#114]
pagination={             
    size: int,             
    page: int,             
    total: int,            
    range: int,            
    onChange(int),         
    position: 'string'     
  }
onChange这个如何给定？
我在构造器内声明绑定了pageChange，然后在pagination={ size:10,onChange:this.pageChange}时，提示Unable to get property 'bind' of undefined or null reference

**Comment by Lobos** [comment]
这个看起来像是 constructor 里面绑定 pageChange 的问题。检查一下看看呢。

**Comment by zhangqhzz** [comment]
constructor 里面  this.pageChange = this.pageChange.bind(this)

**Comment by zhangqhzz** [comment]
给个试过的在table的pagination中用onChange的例子，总感觉哪个地方有问题

**Comment by Lobos** [comment]
https://github.com/Lobos/react-example/blob/master/src/components/author/TableList.js

**Comment by zhangqhzz** [comment]
onChange中要处理的内容不一样，我是要进行this.setState

**Comment by zhangqhzz** [comment]
我的pagechange(page,sidx,sord){ 
         if(sidx===undefined){ 
            this.setState({page:page})
         }else{ 
            this.setState({page:page,sidx:sidx,sord:sidx})
        }
      }
onChange：应该如何写？

**Comment by zhangqhzz** [comment]
onChange:(page,sidx,sord)=>this.pageChange.bind(this,page,sidx,sord) 这样可以吗？

**Comment by zhangqhzz** [comment]
其他部分不用管，我有做部分js文件的修改

**Comment by Lobos** [comment]
https://github.com/Lobos/qenya/blob/master/frontend/components/Schema/Data/index.js

**Comment by Lobos** [comment]
pagechange(page,sidx,sord){
if(sidx===undefined){
this.setState({page:page})
}else{
this.setState({page:page,sidx:sidx,sord:sidx})
}
}

这段是copy出来的代码？好像pagechange 名称和 bind 那里的不一致，Change 没大写

**Comment by zhangqhzz** [comment]
这个例子<Pagination 是单独在用，不是Table中的属性pagination在用

**Comment by zhangqhzz** [comment]
谢谢，是哦，没大写

**Comment by zhangqhzz** [comment]
谢谢，好了，晕，大小写搞死了，您的控件很好，我在学习，为我的需要作相应修改，再次表示感谢
