### ISSUE TITLE
地址打不开。

### ISSUE THREAD

**Issue by InitialCC** [Lobos/react-ui#122]
大佬为啥 http://lobos.github.io/react-ui/ 地址打不开了。

**Comment by vipcxj** [comment]
能打开的~

**Comment by leo-yt** [comment]
![image](https://user-images.githubusercontent.com/18398571/54804644-342f1780-4caf-11e9-80bc-e4fcd8e965a4.png)

**Comment by Lobos** [comment]
原来文档引用的 cdn 地址挂了，已修复。
