### ISSUE TITLE
表格支持 remote data source 吗

### ISSUE THREAD

**Issue by luqin** [Lobos/react-ui#14]

**Comment by Lobos** [comment]
目前是支持的，可以用dataSource。但是以后的版本里考虑移除dataSource，采用redux之类的数据管理。

**Comment by luqin** [comment]
能给个redux的示例吗？

**Comment by Lobos** [comment]
Redux看官方的文档吧，http://redux.js.org/docs/basics/UsageWithReact.html
React UI 里面的组件应该是Dumb Components，在这之上的Page之类的组件应该是Smart Components。
其实不用Redux，用Flux，Reflux之类的也是一样的，这些UI组件只呈现界面，不处理数据，交给上层来处理。

**Comment by luqin** [comment]
跨平台的table分页组件，有什么建议没

**Comment by Lobos** [comment]
跨平台是指什么？

**Comment by luqin** [comment]
react dom、react native。主要是逻辑与ui分离

**Comment by Lobos** [comment]
把数据处理和View分开，数据全部通过props传入
