### ISSUE TITLE
Cannot find module "Qwest"

### ISSUE THREAD

**Issue by xiaowei1118** [Lobos/react-ui#17]
![image](https://cloud.githubusercontent.com/assets/8777672/11553069/27ae6136-99c6-11e5-831c-ac7b17563378.png)
请问是什么问题？

**Comment by Lobos** [comment]
安装一下
npm install qwest

**Comment by xiaowei1118** [comment]
我是在前端直接引用的reactui.js,就算下载下了qwest模块，要怎么用呢？

**Comment by Lobos** [comment]
你是用的build的reactui.js么，build的时候把qwest选进去

**Comment by haoliangwu** [comment]
选了qwest生成的好像也少这个模块。
如下：
exports.Qwest = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"Qwest\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));

**Comment by xiaowei1118** [comment]
我也选了，可是还是报错

**Comment by haoliangwu** [comment]
等他们更新吧，这个应该是build的问题。

**Comment by haoliangwu** [comment]
你如果会用webpack，可以自己build一个，我是为了图个方便，结果- -0。

**Comment by xiaowei1118** [comment]
然而我并不会用webpack

**Comment by haoliangwu** [comment]
@xiaowei1118 你还要这个的bundle吗?我build了一个临时的，我邮件发给你啊

**Comment by xiaowei1118** [comment]
ok,谢谢。twist.zheng@coryphaei.com

**Comment by Lobos** [comment]
sorry，确实有问题，已修复。
