### ISSUE TITLE
Select的clickAway有异常

### ISSUE THREAD

**Issue by haoliangwu** [Lobos/react-ui#18]
```
Uncaught TypeError: Cannot read property 'firstChild' of undefined @ ReactUI.js:7027 
findComponentRoot @ ReactUI.js:7027
findReactNodeByID @ ReactUI.js:6991
getNodeFromInstance @ ReactUI.js:6497
findDOMNode @ ReactUI.js:14237
Component.getClickAwayEvent.fn @ ReactUI.js:3825
```

这个我也不确定是不是我使用不当或者配置不当而引起的，我google了一下，大部分情况都说是由于同时有两个不同版本的react实例而引起的，所以我尝试使用同一版本的react。我本地的react一开始是0.14.3，我看你server上的那个是0.14.0，但是我换成0.14.0依旧报错。

但是这个react不是已经在webpack中被当做external了吗？

我本地访问docs的site里面的select可以正常使用，在自己的project里面就会报上面的异常，实在不知道因为什么了，大神有时间帮看看吧，谢谢

***
![nimbus-image-1450347736950](https://cloud.githubusercontent.com/assets/6328186/11867323/67bd4b7c-a4eb-11e5-96aa-4a3b7360c28d.png)

**Comment by Lobos** [comment]
react 用0.14.0和0.14.3应该没什么关系。信息太少了，不太能确定原因，看下你的项目里require的react，有没有require大写的React

**Comment by haoliangwu** [comment]
谢谢，明天我仔细查查看，有什么新发现我再来补充其他的信息。

**Comment by haoliangwu** [comment]
@Lobos 有可能和babel-loader的版本有关系吗？因为我看见你使用了一些es6较新的语法，像装饰器这种的目前好像在babel6好像有点小问题，我本地是babel6，那个下载的build是babel5，不同babel编译出的代码在一起工作会不会不和谐?

我今天有空把我这里降级成babel5试试。

**Comment by haoliangwu** [comment]
我刚才把我自己的那部分代码分割出去了，单独使用reactUI的select做了一个小demo，还是会报错，所以我怀疑是不是loader的问题。

**Comment by haoliangwu** [comment]
demo
```
[Demo.zip](https://github.com/Lobos/react-ui/files/66157/Demo.zip)

**Comment by Lobos** [comment]
原来你是这样用的啊，既然自己打包了，就不要用生成的那个文件了，直接用npm install rctui，那个是提供给不打包的同学们用的。

**Comment by haoliangwu** [comment]
感谢，看来还是我自己画蛇添足了


If you have any questions, please let me know.

---

Sincerely,
Haoliang "Lyon" Wu
CN QA Engineer
liferay.com

Enterprise. Open Source. For Life.



在 2015年12月18日 上午11:23，陆放 <notifications@github.com>写道：
