### ISSUE TITLE
在 npm install rctui 时报错，问下什么问题？

### ISSUE THREAD

**Issue by ggchxx** [Lobos/react-ui#2]
npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/ZBMOBI/React/scada/npm-debug.log
ZbmobideMacBook-Pro:scada zbmobi$ sudo npm install rctui
npm WARN package.json scada@1.0.0 No repository field.
npm WARN peerDependencies The peer dependency react-router@^0.13.3 included from rctui will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "rctui"
npm ERR! node v0.10.35
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-router does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer rctui@0.3.1 wants react-router@^0.13.3

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/ZBMOBI/React/scada/npm-debug.log

**Comment by Lobos** [comment]
升级一下nodejs的版本试试呢，一直没出现过这个问题啊

**Comment by ggchxx** [comment]
升级到node -0.12.7 还是报错，我的react-router 是v1.0.0 beat3
有影响不？

**Comment by ggchxx** [comment]
找到问题了  install rctui 与 react-router@1.0.0-beta3 冲突，我把react-router删掉就可以了安装了。能解决下这个问题不？

**Comment by Lobos** [comment]
npm 删除了 react-router 依赖
