### ISSUE TITLE
Did you ever thought about scoper css?

### ISSUE THREAD

**Issue by young-cowboy** [Lobos/react-ui#20]
I saw your demo, all components style is in a global scope.Avoid effected by other style which in global scope,Did you ever thought about scoper css?

**Comment by Lobos** [comment]
我在某个版本里用的是css modules，但是为了轻量化，用的是purecss，以后肯定会加入其它ui的，于是加了一个theme。当时考虑到用全局的这种方式比较容易实现theme，别人引用这个库之后，有些不满意的地方，也可以覆盖掉。事实上最近我也在纠结要不要改回css modules。

**Comment by young-cowboy** [comment]
是否考虑把scoper开放给使用者配置，让他们去选择是否需要scoper?

**Comment by Lobos** [comment]
选择配置不太容易实现吧，css module的style写法和正常的写法不太一样。

**Comment by luqin** [comment]
UI 组件使用 css module 好吗？用户需要定制主题怎么办？
