### ISSUE TITLE
webpack 打包，报错，不知道什么原因？

### ISSUE THREAD

**Issue by LiangKevin** [Lobos/react-ui#21]
You may need an appropriate loader to handle this file type.
| "use strict";
| 
| export const Checkbox = require('./Checkbox');
| export const CheckboxGroup = require('./CheckboxGroup');
| export const Datetime = require('./Datetime');
 @ ./src/public/js/index/index.js 7:14-30

webpack配置：
{
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel',
                query: {
                    cacheDirectory: true,
                    presets: [
                        'es2015',
                        'react'
                    ],
                    plugins: ['transform-runtime']
                }
            },

**Comment by Lobos** [comment]
应该是有loader没有安装，看看这些装了没，babel-preset-es2015，babel-preset-react

**Comment by LiangKevin** [comment]
都装了的，编译别的组件都正常的

**Comment by LiangKevin** [comment]
找到原因了，exclude: /(node_modules|bower_components)/,这个
