### ISSUE TITLE
关于react-ui的一些问题以及规划

### ISSUE THREAD

**Issue by Lobos** [Lobos/react-ui#22]
写这篇文章呢，要先给一些同学道个歉，因为最近换了工作，事情比较多，有些同学给我发的gmail（也有因为GFW的原因，时断时续）和提的issue，过了很久才回复。也有位同学让我建个QQ群之类的讨论问题，但是因为工作关系，基本不能用QQ，所以在这里发个帖子，回答一些问题，并且说下后面的规划吧。
# 有了ant-design这样NB的库，是否还有必要继续react-ui

第一个问题，算是自问自答。
react-ui写了一大半的时候，发现蚂蚁金服开源了ant-design这个项目，当时觉得挺迷茫的，因为只有一个人，基本上把工作之余的时间都搭进去了，才做到这个程度。和蚂蚁金服相比，一堆牛人，有很NB的设计，官网很酷炫，文档也很健全。
那个时候反复的思考，这个项目还有没有继续下去的必要。仔细对比了一下，发现还是可以做下去的。
react-ui是一个完全从易用性的角度去思考的一个库，原则是调用的时候，越简单越好，写的代码越少越好，即使某些地方不符合react思想的。
比如select，react-ui的调用方式

```
<Select placeholder="Group by continent"
  groupBy="continent"
  filterAble={true}
  optionTpl='<img src="images/flags/{code}.png" /> {country}-{en}'
  valueTpl="{country}-{en}"
  data={dataSource("json/countries.json", null, {cache: true})} />
```

ant-design的调用方式

```
<Select defaultValue="lucy"
    style={{width:200}}
    showSearch={false}
    onChange={handleChange}>
    <OptGroup label="Manager">
      <Option value="jack">jack</Option>
      <Option value="lucy">lucy</Option>
    </OptGroup>
    <OptGroup label="Engineer">
      <Option value="yiminghe">yiminghe</Option>
    </OptGroup>
  </Select>
```

同样的还有CheckboxGroup，Tree等等。
有人说ant的方式是更符合react的思想的，同时更加的灵活。我同意。
但是我的想法是，一个好用的组件，使用者只需要传一组数据进去，并不要知道组件内部的结构是什么，就可以完成这个组件的调用。并且同一组数据，只改一下调用，就可以实现类似Select到Radio的转换。

```
<RadioGroup textTpl={'{country}-{en}'} data={dataSource("json/countries.json", null, {cache: true})} />
```

为了更加方便的调用，创建了[FormControl](http://lobos.github.io/react-ui/#/formControl)这个组件，把所有的表单组件注册到FromControl，在这个FormControl上实现自动的validate，自动的tip。这样从而避免在表单组件外面再加一个Validator，这个是我不愿意接受的。

同样的，还有Modal，Message这样的组件，使用的时候完全不像React的组件，更接近传统的JS库，只提供了静态方法，在任意的地方调用。

另外，大家都说，有redux，有flux，所有的数据都应该通过props传入，这样才符合规范，才是现代化的。但是对我来说，就是喜欢简单粗暴的传入一个链接地址获取数据。我只是想给select几个选项值，要去写action，写store，写reducer，connect……OMG！
当然，如果你喜欢props，你仍然可以直接传入data。
# 为什么要用purecss

最初的版本里，css部分是用的bootstrap，慢慢的发现不能接受了，因为bootstrap差不多有100多kb的体积，而那个时候整个js库的文件也才60多kb。当时想了很多方案，最后选了yahoo的purecss，因为非常的小，只有20kb不到，并且官网的文档里也明确说明可以和bootstrap搭配使用。
不过purecss确实是比较简陋，所以在项目里加了一个theme的模块，可以对css进行扩展。是有打算做一些热门ui的皮肤，但是一直搁置中。
另外在某个版本里，使用了css module的方式来防止css污染，不过这样不能方便的扩展，所以又换回了'rct-'这个前缀。现在还是会比较纠结是否使用css module的问题，打算等后面重构css部分的时候再做决定。
# 为什么没有拆分成独立的子项目

这个问题也困扰了我一段时间，因为有些同学用react-ui，只是看重了某一个组件。而且，从理论上来说，一个单独的组件比整个UI库更好维护啊。
于是就建了一个rctui的group，把整个项目分拆。后来发现随着组件的拆分维护工作进入了一个地狱，比如utils这个库改了一行代码，用到它的Button要升级，用到Button的其他库也要升级，都要push到github，publish到npm。然后发现其他所有用到utils的库都在等着升级……
所以又回到一个库的状态，但是还是有点纠结。直到后来听了一个facebook大神的讲课，说facebook只有一个仓库，全部的代码都在上面。
好吧，不纠结了。
最后就是发布到npm之前费点事，把代码从src挪到根目录下面，只需要某个组件的话可以单独引用。
# 尽可能的轻

这个是react-ui保持一个完整的库的另一个原因，如果拆分成很多库，再通过一个项目合起来的时候，不可避免的会增加很多冗余的代码。
从一开始，就一直在避免整个项目变得太庞大。因此放弃了underscore、lodash这样的神器，所有的utils都是自己写，或者从别的库里一点一点的剥出来。也因为这个原因，迟迟没有升级到es6（babel转换后大约会增加1/4左右的体积），后来终于没有忍住，一下升到es7（再后来，这变成了一个悲伤的故事）。
其他的部分，比如Grid，使用了一个动态的方法生成css，用几kb实现了一个任意多列等分、支持responsive的栅格系统，从而减少了几十kb css的加载。不过因为生成了很多style标签，暂时没有想清楚是否有问题。
此外，ajax库的选择，最初的时候是用了superagent，算是比较轻量的了，差不多20多kb，但是还是觉得比较重，那个时候js部分只有60多kb。选了n个ajax库，最后选了一个几乎没多少人知道的qwest，因为它是Promise A+P规范，因为它只有7kb。
# 不能解决所有问题

我给一个同事讲（吹嘘）我的table的时候（因为我觉得react-ui的table写的还蛮NB的），他就问如果要多层表头，你怎么办？如果要合并单元格，你怎么办？我就哑口无言咧。
后来就慢慢想通了，react-ui的实现方式，在灵活性上是有一些缺失的，确实有很多问题解决不了的。事实上，也没必要去解决所有的问题，只要去解决大多数场景的问题。如果可以用20%的时间解决80%的问题，那就很完美了。
# 下一个版本的规划

有个同学给发邮件给我说，0.5.0到0.5.2，改了很多代码，其实90%是因为babel从5升到6，发现一些es7的语法不支持了，所以干脆把所有es7的代码全改了。这个事情说明，步子迈大了，确实会扯到蛋的……

0.6 应该会是真正的改很多代码，目前的规划以重构为主：
- 在线build的部分，facebook已经官方推荐babel了，也没精力维护，就去掉了。
- 任意等分的[Grid](http://lobos.github.io/react-ui/#/grid)，这个0.5.2已经实现了。
- 对dataSource和qwest还是不太满意，在qwest的基础上封装了一个[refetch](https://github.com/Lobos/refetch)，Promise A+规范，不需要polyfill，支持jsonp，cache。
- dataSource不再从data传入（接口会保留两三个版本吧），使用一个新的属性fetch，支持promise和options两种方式，内部使用higherorder component方式封装。
- validate从FormControl拆分到各个表单组件，目前的这种方式对于一行多个组件实现起来有问题。应该也是higherorder component的方式。
- 因为封装了两层higherorder component的原因，FormControl的getValue应该会取消，并且直接调用组件内部的方法并不太好。取消了会带来一些问题，获取Form值是否通过组件的name来实现？还得想另一个方法来实现Form提交前自动的validate。

0.7 会以css为主，使用autoprefixer代替目前的mixins，考虑加一两套皮肤。

另外，单元测试。目前utils下面基本所有的代码都通过了单元测试。component的测试比较麻烦，一直也没精力完成，但是后面也要做的。

很多同学的问题都是webpack打包的，其实很多大神，Dan啊，tj啊都写了start kit的，可以参考他们的，后面有空也会写个简单的。

最后，大家对react-ui这个库有什么看法、建议和问题，或者希望增加哪些组件，都可以在这里提出来，我会尽力解决的。发issue和邮件也可以。

**Comment by afc163** [comment]
这么好的帖子居然没有人回。

首先，UI 组件库是一件起步的成本很低，但是极难做好的事情，@Lobos 以一己之力实现了这么多组件，接口、代码、控件交互、文档质量都相当高，个人非常钦佩，当时我和同事说的原话是“快把这个人挖过来啊”。Ant Design 在做的过程中，也参考过 react-ui 的 API 和交互形式。

Ant Design 现在的问题同样是维护人力太少，我们前期参与的人员较多，但是沉淀下来主要的维护人员就那么三四个。接口的统一、日常维护、向下兼容的压力、新技术的探索都比较吃紧。其实 react-ui 反而都没有这些包袱，建议 @Lobos 可以跑的更快更远一些。

DataSource 这块，原来 antd 中 Table 也有一个类似的实现，由于内部对 flux & redux 的实践，组件只做比较纯粹的 View 展现和数据收集点确实比较合适，后来就都去掉了。不过楼主的尝试也是一种思路，在很多展现型的小场景确实有市场 。

期待新版本的 react-ui 。

> 有换工作的想法，联系我。:smile:

**Comment by singba** [comment]
前n年一直做桌面及服务程序开发，今年开始看前端的库，接触到react后就迷上了

我觉得封装控件最重要就是要简单，基本使用的时候，把关键参数写好，如lobos说的select。如果需要扩展（比如提到的table多层表头），另外再继承封装一个，架构师就是帮程序员做好选择。

关于版本的规划，建议考虑将常用布局、实例等做一些，这样对于新手会有更多的吸引力，

我是先接触antd的，直到最近有人介绍了lobos的这个，我想说非常喜欢，尤其是FormControl的设计。我觉得你可以加入antd，但希望这个还继续开发下去，虽然我现在还没有使用，那只是因为我目前的功力还不够应付所有的坑。

加油！

**Comment by yelingfeng** [comment]
走自己风格就好 你已经很牛逼了

**Comment by haoliangwu** [comment]
走自己的路就好了，另外单元测试那块我可以帮你一些忙，:)。

**Comment by sukui** [comment]
我最早接触的是 react-ui

**Comment by Lobos** [comment]
@afc163 哈哈，没想到你会回帖啊。antd这种组织方式维护成本确实应该非常高的。现在我改一些接口也会想跟上个版本不兼容了咋办，但是心一横也就改了。

DataSource我觉得像table这种用不用都没什么，而select这种组件我是觉得比较需要，这种本身就是比较小的组件，如果一个表单里有很多这种数据选项，每一个都单独去写一套action、store，使用者的维护成本会很高。

**Comment by Lobos** [comment]
@singba 我有一段时间没有加新的组件了，还是对现在的架构还不是特别满意，特别是FormControl，稍微有点重。短期的目标是把架构稳定了，布局组件什么的再慢慢加。

**Comment by Lobos** [comment]
@yelingfeng @sukui 多谢鼓励，多提些建议嘛：）

**Comment by Lobos** [comment]
@haoliangwu 那真是求之不得啊：）

**Comment by haoliangwu** [comment]
@Lobos 
test里面的component单元测试最好能给个example，因为所有相关test的config好像还没写完吧。你是准备用mocha + jsdom + react.TestUtils来做吗？我对jsdom的使用不是特别熟悉，自己公司的单元测试都是用karma跑在浏览器上的，如果有个example参照的话，就可以帮你设计一些针对不同组件的单元测试了。

**Comment by Lobos** [comment]
@haoliangwu 
不要用jsdom了，一开始是打算用jsdom的，但是jsdom有问题，就搁置了。

**Comment by haoliangwu** [comment]
@Lobos 
不用jsdom的话，那准备怎么做？既然项目是用webpack构建的，那么用mocha-loader配合浏览器靠谱吗？

**Comment by Lobos** [comment]
@haoliangwu 用mocha＋phantomjs + react.TestUtils吧。

**Comment by yiminghe** [comment]
诚邀加盟 [react-component](http://github.com/react-component) / [antd](http://github.com/ant-design) . 后续还有 native／mobile ， 大有可为

**Comment by JasonJie** [comment]
你好，我在用webpack打包后 自动把React 打包为_react，但是最后在React.createElement引用的是React不是_react 所以报错React is not defined 请问有什么方案去解决的吗

**Comment by haoliangwu** [comment]
@JasonJie 
React is not defined并不一定是webpack的问题，我遇到过的情况，包括没有引入额外的React.js和加载了不同版本或者重复的React实例，你试试看有没有这些问题。

**Comment by haoliangwu** [comment]
@Lobos 
haoliangwu@3fcc44a833f7e6f07e68024a954762e6b6792fb0
随便写了写，启动devServer以后，运行npm run test-component，是这个意思吗？

**Comment by lucubrator** [comment]
一个人搞了这么多东西，还是开源，顶

**Comment by tianmaoyu** [comment]
加油！

**Comment by GuoYongfeng** [comment]
很遗憾，这么晚才关注到这个issue，其实很早之前就在看lobos写的react-ui，当时一直也在思考一个问题，有了组件化的支持后，在项目中引入react，发展到最后，瓶颈大部分压在组件上面。

我们在进行企业级应用开发的时候，最迫切的需求也是能够在内部沉淀一套组件库来支撑业务发展，并为开源做一些贡献。

lobos同学以一己之力做到现在已经很棒，希望继续加油。。。

**Comment by hl85** [comment]
写的很实在，强烈共鸣。建议作者在线招募一个团队一起维护，你来提供架构思路，设计原则，维护团队人员更迭。如果不行，就去antd吧，薪水应该会让你满意。希望项目能继续迭代起来。

**Comment by Lobos** [comment]
多谢鼓励啊。坏消息是，antd应该是去不了了。好消息是，这个项目会一直进行下去。
其实这个项目一直在进行中，0.7在dev分支下，0.8做啥也想好了。无论怎么忙，每个星期至少会投入20到30个小时在这个项目上吧（已经一个多月没有2点前睡觉了...）
现在也不能算是一个人，@haoliangwu 写了很多很多测试代码。真是不知道该怎样感谢了。
