### ISSUE TITLE
Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by ganxunzou** [Lobos/react-ui#27]
你好，我采用你源码的方式：
import { Component, PropTypes } from 'react';
class Input extends Component {
}

运行会报错：Uncaught ReferenceError: React is not defined

必须修改成：
import React , { Component, PropTypes } from 'react';

请问是什么原因呢?

是缺少什么Loader吗？

**Comment by Lobos** [comment]
你的代码里面应该使用了React下面的东西吧

**Comment by haoliangwu** [comment]
猴年快乐，这个问题我写testcase也遇到了，如果webpack配置中，React不作为外部对象导入的话，好像就会有这个问题，因为我在test文件夹的index.html中把cdn替换成本地的React（想着能快点），碰巧遇见了这个问题。

**Comment by Lobos** [comment]
原来是因为没配置webpack的externals，我的理解是这样的，如果不配置的话，webpack生成的代码是没有把 window.React 链接到import 的 'react' 对象的，所以就not define了

**Comment by haoliangwu** [comment]
应该是这样吧，那在不想设置external的情况下，那这种情况怎么解决呢？
我昨天遇到的问题其实是这样的，我使用了一个第三方的react测试库，它依赖react，所以会把react也加载入testBundle中，然后index.html又会有从cdn导入的react，这样就有两个React实例了，会出问题，后来就想干脆不用external，直接用本地的react，之后就遇到这个问题了。

**Comment by Lobos** [comment]
把cdn导入的那个去掉呢

**Comment by haoliangwu** [comment]
去掉cdn的话，也会提示not define,　不过和这个not define应该不一样。我昨天也尝试能不能解决，最终在把源码改成这样
```
import React , { Component, PropTypes } from 'react';
```
就好用了

**Comment by Lobos** [comment]
0.6.1 发布的版本源码编译为es5了

**Comment by Lobos** [comment]
需要这个插件 [babel-plugin-react-require](https://www.npmjs.com/package/babel-plugin-react-require)
