### ISSUE TITLE
[bug:]form中email控件 icon头和后面的输入框错位，没有水平对齐

### ISSUE THREAD

**Issue by Erwin11** [Lobos/react-ui#3]
楼主您好， 
bug:
    form中，email控件的icon头部和后面的input输入框错位了，头比后面的input矮了一些。
解决方案：
    查看css样式，发现可以把
 .pure-form .input-group .addon{
     margin: .25em 0;
}
把这个margin去掉就能水平对齐了。

**Comment by Lobos** [comment]
是的，多谢指出。
