### ISSUE TITLE
 Parse Error: Line 1: Illegal import declaration while parsing file

### ISSUE THREAD

**Issue by mountain3th** [Lobos/react-ui#30]
我用browserify bundle做dev开发的环境，但一旦引用rctui/下的任何一个module就会报错，提示browserify compile error（transform用的是babelify，支持es6语法)

**Comment by Lobos** [comment]
没用过browserify，react ui的组件内部import了css文件，不知道browserify支持不。

**Comment by yursile** [comment]
我也是相同的情况。还换了好几个node版本。

**Comment by Lobos** [comment]
browserify目前应该不支持，用webpack吧
