### ISSUE TITLE
作者来个 tabs 组件吧

### ISSUE THREAD

**Issue by billgo** [Lobos/react-ui#33]
作者来个 tabs 组件吧，感觉这个组件经常用到。

**Comment by Lobos** [comment]
布局的组件暂时还没时间处理，不过后面会有的：）

**Comment by hyndaniel** [comment]
说好的tabs呢。。。

**Comment by haoliangwu** [comment]
估计他太忙了吧，我最近写一了一些简单的layout组件(nav, panel, tabs, list)，不过水品有限。

**Comment by hyndaniel** [comment]
@haoliangwu 请问地址在哪里呢？

**Comment by haoliangwu** [comment]
@hyndaniel 就是这个repo呀，不过是在dev的branch。

**Comment by hyndaniel** [comment]
噢噢，我去看看~谢啦~

**Comment by Lobos** [comment]
0.7 release.
