### ISSUE TITLE
react-ui能跟meteor配套使用吗？

### ISSUE THREAD

**Issue by qiuling2014** [Lobos/react-ui#34]
react-ui能跟meteor配套使用吗？

**Comment by Lobos** [comment]
不太了解meteor，不过感觉应该是不大好。

**Comment by qiuling2014** [comment]
😭

**Comment by Lobos** [comment]
其实如果只是用meteor的做服务端api的话，肯定是没问题的。但是好像meteor的很大一部分优势是跟服务端配套的前端模版。

**Comment by haoliangwu** [comment]
我试过，可以用，麻烦一点，但是meteor好像是配合服务器渲染更好一些。


If you have any questions, please let me know.

---

Sincerely,
Haoliang "Lyon" Wu
CN QA Engineer
liferay.com

Enterprise. Open Source. For Life.



在 2016年3月8日 上午11:22，陆放 <notifications@github.com>写道：
