### ISSUE TITLE
为什么我报错了？

### ISSUE THREAD

**Issue by xfcf1** [Lobos/react-ui#37]
You may need an appropriate loader to handle this file type.
| "use strict";
| 
| export const Checkbox = require('./Checkbox');
| export const CheckboxGroup = require('./CheckboxGroup');
| export const Datetime = require('./Datetime');

loader是
{test: /\.(jsx|js)$/, loader: 'babel-loader', exclude: /node_modules/, query: {
                cacheDirectory: true,
                presets: ['es2015', 'react','stage-0']
            }

**Comment by Lobos** [comment]
缺loader，处理css和图片
```
{ test: /\.(css|less)$/, loader: 'style-loader!css-loader!postcss-loader!less-loader' },
{ test: /\.(png|jpg|jpeg|gif)$/, loader: 'url-loader?limit=10000&name=./images/[name].[ext]' }
```

**Comment by xfcf1** [comment]
还是一样的。。

        loaders: [
            {test: /\.(jsx|js)$/, loader: 'babel-loader', exclude: /node_modules/, query: {
                cacheDirectory: true,
                presets: ['es2015', 'react', 'stage-0']
            }},
            {test: /\.html$/, loader: 'raw', exclude: /node_modules/},
            {test: /(?!\.html)\.jade$/, loader: 'jade-loader', exclude: /node_modules/},
            {test: /\.(css|less)$/, loader: 'style-loader!css-loader!postcss-loader!less-loader', exclude: /node_modules/},
            {test: /\.(png|jpg|jpeg|gif)$/, loader: 'url-loader?limit=10000&name=./images/[name].[ext]'}
        ]


  "devDependencies": {
    "babel-core": "^6.7.2",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.7.2",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "css-loader": "^0.19.0",
    "del": "^2.2.0",
    "file-loader": "^0.8.5",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-inject": "^3.0.0",
    "gulp-jshint": "^2.0.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-rev": "^7.0.0",
    "gulp-uglify": "^1.5.3",
    "gulp-zip": "^3.2.0",
    "html-webpack-plugin": "^1.6.0",
    "jade": "^1.11.0",
    "jade-loader": "^0.8.0",
    "jshint": "^2.9.1",
    "less": "^2.6.1",
    "less-loader": "^2.2.2",
    "postcss-loader": "^0.8.2",
    "raw-loader": "^0.5.1",
    "redux-devtools": "^3.1.1",
    "rev-del": "^1.0.5",
    "run-sequence": "^1.1.5",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.10.1",
    "webpack-dev-server": "^1.10.1"
  }

**Comment by haoliangwu** [comment]
你是以node_modules的方式加载react-ui吗，如果是的话把exclude: /node_modules/去掉或者把react-ui的路径写到include中。

**Comment by Lobos** [comment]
@xfcf1 试下haoliangwu的方法，他应该是对的

**Comment by SelinaYu** [comment]
遇到同样的问题，没有配置exclude：/node_modules/还是不能解决

**Comment by SelinaYu** [comment]
在webpack配置文件添加以下可以解决
resolve: {
		extensions: ['', '.js'],
		modulesDirectories: ['node_modules']
	},

**Comment by huaziHear** [comment]
上面提到的方法都试了一遍，没有解决这个问题。

**Comment by xfcf1** [comment]
这个问题解决了 
首先，要用升级到babel6，然后js loader 这里 要包括 react ui 的目录， 因为他是es6写的 需要编译。
第二，加上babel6以后 也许会发现报错 react 未定义，那么只要在webpack里面把react expose就行了
```js
{test: /react\.js$/, loader: 'expose?React'}
```
