### ISSUE TITLE
使用reactui,安装完之后为什么会保证错？

### ISSUE THREAD

**Issue by 1037359589** [Lobos/react-ui#39]
编译出一堆警告
<img width="563" alt="56ecb57f-e18f-4b3f-af44-89810c80edcc" src="https://cloud.githubusercontent.com/assets/11945274/14487388/d4c6fe74-0194-11e6-821d-cf0afe6c5f48.png">
浏览器还报错
![5c737eaa-073e-4be2-a67e-51eeb90d0b01](https://cloud.githubusercontent.com/assets/11945274/14487422/fae5fdc6-0194-11e6-9f53-150d50879a88.png)
求大神解答！！！，急急急！！！！

**Comment by haoliangwu** [comment]
那不是写了吗，你需要一个合适的loader来编译这种文件类型，就是指.less文件类型。

**Comment by 1037359589** [comment]
解决了，要import less文件，谢谢了，文档没说要加less文件，有点坑！！！
