### ISSUE TITLE
demo中的整数输入框, 无法直接输入负号

### ISSUE THREAD

**Issue by wvq** [Lobos/react-ui#42]
RT,  如-1, 按顺序输入"-", "1"的话,负号无法输入, 反之先输入数字部份,再在前面输入负号可以成功

**Comment by haoliangwu** [comment]
是bug，可以临时先这么改
haoliangwu@bf841ecc4bede16b3b4471e8a7e310026dbd07b6

**Comment by Lobos** [comment]
多谢多谢，已经改了。
