### ISSUE TITLE
0.7 开发规划，日志

### ISSUE THREAD

**Issue by Lobos** [Lobos/react-ui#45]
#0.7 开发规划

react ui 0.7版的规划放在这里吧。有什么想法也可以在这里讨论。

**先说下目标吧，0.7主要是解决theme的问题。**
之前因为项目赶着用，加了一套theme在项目里的，因为没什么时间，是很粗暴的把purecss复制了一份，改了一些数值。加载的时候，通过动态拼接require资源地址来实现。

```
// theme.js
let THEME = 'pure';

function requireCss(pack) {
  require(`./${theme}/${pack}.less`);
};

function setTheme(theme) {
  THEME = theme;
}

// component.js
requireCss('button');
```

这个临时方案虽然可以实现，但是非常low，所以决定开个版本解决theme的问题。

**0.7 计划使用bootstrap作为基础样式库**
这个项目一开始的时候，是用的bootstrap作为样式库。那个时候还没有按需打包，整个js才50KB，而一个bootstrap就100多KB了，觉得太划不来，所以用了purecss。现在来看，一是purecss太过小众，而且已经年久失修，跟不上时代了；二是做theme的话，需要大量的配置，purecss改起来成本太高。还是傍着bootstrap这条大腿吧。鉴于bootstrap 4.0已经抛弃less使用sass，所以会尝试使用sass。

0.7的整个theme的结构目前构想是这样的。

```
|- styles/
  |- themes/
    |- _bootstrap.scss
    |- _other_theme.scss
    |- ...
  |- _buttons.scss
  |- _checkbox.scss
  |- ...
|- Button.js
|- Checkbox.js
|- ...
```

只留一份组件的scss文件，不同theme抽取出变量放到themes下面。bootstrap.scss作为基础库，提供默认值。其他的theme通过import这个基础库，用自定义的变量覆盖掉默认值。
bootstrap.scss 和 mixins 定期同步 boostrap 4.0 的文件到项目里，文件保持和bootstrap一致，方便以后直接使用bootstrap的theme。
bootstrap.scss

```
$gray-dark:                 #373a3c !default;
$gray:                      #55595c !default;
$gray-light:                #818a91 !default;
$gray-lighter:              #eceeef !default;
$gray-lightest:             #f7f7f9 !default;

$brand-primary:             #0275d8 !default;
$brand-success:             #5cb85c !default;
$brand-info:                #5bc0de !default;
$brand-warning:             #f0ad4e !default;
$brand-danger:              #d9534f !default;
```

other_theme.scss

```
@import 'bootstrap.scss';

// color ==================================================
$brand-primary:      #337ab7;
$brand-success:      #5cb85c;
$brand-info:         #5bc0de;
```

buttons.scss 默认引入bootstrap.scss文件

```
@import "themes/bootstrap";

:local(.button) {
  line-height: @base-line-height;
  padding: @btn-padding;
  color: @btn-color;
  border: 1px solid @btn-border;
  background-color: @btn-bg;
  border-radius: @btn-radius;
  ...
```

Button.js 引入button.scss

```
import styles from './styles/buttons.scss';
...
// 利用 css-loader 实现 css-module 的功能
className = classnames(styles.button, ...);
...
```

到这里为止，除了local css（css-module）这个以外，用户在使用上和之前的版本没有多大区别。如果使用者需要使用其它的theme，可以安装rctui-theme-loader，在webpack里加一个preLoader配置。

```
module: {
  preLoaders: [
    { test: /\.scss$/, loader: 'rctui-theme-loader?theme=other_theme' }
  ]
}
```

其实这个loader做的事情很简单，在webpack处理scss文件之前，把 @import 'themes/bootstrap' 替换成指定的theme文件。

```
module.exports = function (content) {
  var query = loaderUtils.parseQuery(this.query);
  if (query.theme) {
    content = content.replace('themes/bootstrap', `themes/${query.theme}`);
  }
  return content;
}
```

在考虑后面theme-loader可以引入外部的配置文件，覆盖内置的配置。不过先把目前的工作完成再说。

**Comment by Lobos** [comment]
高阶组件原来加载的地方有点乱，加了curry和compose。
把Checkbox、CheckboxGroup、Radio、RadioGroup改成Dumb组件了，手工测了下性能，稍微优化了点。发现加了FormItem这层以后，原来的Form组件基本都可以改造成Dumb组件，后面能改的全都改了。
加了一个Transition组件处理动画。

**Comment by Lobos** [comment]
Rating，Datepicker 重写完，困...

**Comment by toddlxt** [comment]
佩服，加油！！！
