### ISSUE TITLE
关于Form验证部分的疑问

### ISSUE THREAD

**Issue by janryWang** [Lobos/react-ui#53]
Form验证，通常是存在一个主动校验和被动校验的过程，主动校验就是点击submit提交，如果某些表单验证失败，那么不会触发提交，但是会触发所有表单的错误消息显示，被动校验就是经过onChange，onBlur或者onFetch这些事情来校验的，我想问问你在主动校验这一块是如何设计的呢？还有，第一次访问表单，错误消息通常是不会被显示的，但是校验还是会走一遍，这个不显示你是怎么控制的呢？还有一些场景下希望submit按钮是随着整个表单的验证状态而变化，置灰或者不置灰，或者还显示一个加载状态之类的

**Comment by Lobos** [comment]
目前大部分Form的设计是传入fields的对象，通过这个对象进行操作。我为了让使用更简单，没有采用这样的设计。而是在内部使用了一组方法itemBind，itemUnbind和itemChange，把FormItem绑定到Form上。主动校验就是Form里面遍历items的validate方法，被动就是FormItem change的时候调用itemChange把结果给Form。第一次访问，value是从props直接拿的，不会出发itemChange事件，所以不显示错误消息。submit置灰这个功能我应该没实现，理论上来说，Form内部是可以拿到所有绑定的item的状态的，所以应该没问题的。

**Comment by janryWang** [comment]
好的，感谢，对了，我还有一个疑问，就是，为什么Form要有一个布局属性layout这样的属性呢？但是FormControl却有grid属性来控制布局，首先，我个人觉得跟布局相关的应该最好不要和组件耦合在一起吧，而且布局这一块，如果是属于某一个集成解决方案中的，那也应该统一起来吧，不应该一下子用layout一下子用grid吧，这样会让人比较困惑，目前我在我们团队中就是打算把布局这一部分抽象出一系列的布局组件出来，比如Grid，Flex，然后还有一些场景化的布局组件，偏业务场景的，Grid这部分觉得你做的Grid非常赞，几乎解决了我们在网格布局中80-90%的痛点，太牛逼了，只是对于Form这部分提供的布局属性还是存在一些分歧，不知道你设计的时候是如何考虑的

**Comment by Lobos** [comment]
layout 是控制 inline，stacked 和 aligned 整体的结构的，grid是控制局部的，还是有点不一样的。而且 aligned 这种布局很多情况下左侧的label是固定宽度的，用grid就不太方便了。

**Comment by janryWang** [comment]
如果要控制整体布局，是否可以做一个InlineForm/StackedForm/AlignedForm这样的组件来全局控制呢？我始终觉得用组件化来描述布局是比较好的，因为样式的东西最好是能和交互分离开来

**Comment by Lobos** [comment]
可以啊，不过写三个组件，体积稍微会大一点，对使用者来说，需要多了解三个组件。

**Comment by janryWang** [comment]
如果按照交互型组件和布局型组件来分类的话，我个人认为是职责更加清晰，同时也更加容易理解，当然，都是建议哈
