### ISSUE TITLE
升级react v15.2后有unknown props的warning

### ISSUE THREAD

**Issue by haoliangwu** [Lobos/react-ui#55]
这个需要修复吗？好像是需要把一些扩展运算符拷贝props的对于子元素无用的prop筛选掉。

**Comment by Lobos** [comment]
修吧，看了下，还算好，没想象的多，utils里面加个 {...filterInputProps(props)}，估计还要一个 {...filterSvgProps(props)}

**Comment by haoliangwu** [comment]
好像还有一个textarea，一会看看。


If you have any questions, please let me know.

---

Sincerely,
Haoliang "Lyon" Wu
CN QA Engineer
liferay.com

Enterprise. Open Source. For Life.



2016-07-26 11:01 GMT+08:00 Lobos <notifications@github.com>:

**Comment by haoliangwu** [comment]
#56
