### ISSUE TITLE
react.min.js:14 Uncaught TypeError: this.refs.table.getChecked is not a function

### ISSUE THREAD

**Issue by likun7981** [Lobos/react-ui#58]
@Lobos 
Uncaught TypeError: this.refs.table.getChecked is not a function
[table 0.6](http://lobos.github.io/react-ui/0.6/#/table)

**Comment by Lobos** [comment]
文档错了，已经改成getSelected了...
不过因为HOC的原因，这个方法0.7之后会废除掉，改成其他的方式。
