### ISSUE TITLE
react-ui需要修改配置文件才能在我自己的项目里面引用吗

### ISSUE THREAD

**Issue by kakusang** [Lobos/react-ui#59]
我在自己的react项目里面不能直接引用这些封装好的组件，我需要修改什么配置文件吗

**Comment by haoliangwu** [comment]
试试cli

**Comment by Lobos** [comment]
嗯，可以用内置的cli，不过注意，会覆盖webpack-config文件和改动package.json（插入依赖之类的）
node node_modules/rctui/cli/init.js [options]
options:
    - all        安装／升级依赖包，增加demo文件，devServer服务，webpack配置
    - update     只安装／升级依赖包
    - demo       一个简单的demo
    - server     在项目根目录下添加一个devServer.js文件，可以通过 node devServer.js 启动
    - webpack    在项目根目录下添加一个webpack.config.js文件，注意备份原来项目里的webpack配置文件

**Comment by kakusang** [comment]
不好意思，今天有点忙忘了及时回，用cli后也没成功，这是什么原因

**Comment by haoliangwu** [comment]
@kakusang 
贴点log上来吧，要不了也不好判断哪方面问题，毕竟webpack配置设计到的东西有点广。

**Comment by kakusang** [comment]
WARNING in ./~/rctui/themes/pure/upload.less
Module parse failed: F:\react\react+redux教程\todos-with-undo_me\node_modules\rc
tui\themes\pure\upload.less Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (F:\react\react+redux教程\todos-with-undo_me\node_modules
\webpack\node_modules\acorn\dist\acorn.js:923:13)
    at Parser.pp.getTokenFromCode (F:\react\react+redux教程\todos-with-undo_me\n
ode_modules\webpack\node_modules\acorn\dist\acorn.js:2831:8)
    at Parser.pp.readToken (F:\react\react+redux教程\todos-with-undo_me\node_mod
ules\webpack\node_modules\acorn\dist\acorn.js:2526:15)
    at Parser.pp.nextToken (F:\react\react+redux教程\todos-with-undo_me\node_mod
ules\webpack\node_modules\acorn\dist\acorn.js:2518:71)
    at Parser.parse (F:\react\react+redux教程\todos-with-undo_me\node_modules\we
bpack\node_modules\acorn\dist\acorn.js:1631:10)
    at Object.parse (F:\react\react+redux教程\todos-with-undo_me\node_modules\we
bpack\node_modules\acorn\dist\acorn.js:885:44)
    at Parser.parse (F:\react\react+redux教程\todos-with-undo_me\node_modules\we
bpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (F:\react\react+redux教程\todos-with-undo_m
e\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (F:\react\react+redux教程\todos-with-undo
_me\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:
10)
    at nextLoader (F:\react\react+redux教程\todos-with-undo_me\node_modules\webp
ack\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
 @ ./~/rctui/themes ^\.\/.*\.less$

WARNING in ./~/rctui/themes/pure/variables.less
Module parse failed: F:\react\react+redux教程\todos-with-undo_me\node_modules\rc
tui\themes\pure\variables.less Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (F:\react\react+redux教程\todos-with-undo_me\node_modules
\webpack\node_modules\acorn\dist\acorn.js:923:13)
    at Parser.pp.getTokenFromCode (F:\react\react+redux教程\todos-with-undo_me\n
ode_modules\webpack\node_modules\acorn\dist\acorn.js:2831:8)
    at Parser.pp.readToken (F:\react\react+redux教程\todos-with-undo_me\node_mod
ules\webpack\node_modules\acorn\dist\acorn.js:2526:15)
    at Parser.pp.nextToken (F:\react\react+redux教程\todos-with-undo_me\node_mod
ules\webpack\node_modules\acorn\dist\acorn.js:2518:71)
    at Parser.parse (F:\react\react+redux教程\todos-with-undo_me\node_modules\we
bpack\node_modules\acorn\dist\acorn.js:1631:10)
    at Object.parse (F:\react\react+redux教程\todos-with-undo_me\node_modules\we
bpack\node_modules\acorn\dist\acorn.js:885:44)
    at Parser.parse (F:\react\react+redux教程\todos-with-undo_me\node_modules\we
bpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (F:\react\react+redux教程\todos-with-undo_m
e\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (F:\react\react+redux教程\todos-with-undo
_me\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:
10)
    at nextLoader (F:\react\react+redux教程\todos-with-undo_me\node_modules\webp
ack\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
 @ ./~/rctui/themes ^\.\/.*\.less$

WARNING in ./~/rctui/themes/pure/tables.less
Module parse failed: F:\react\react+redux教程\todos-with-undo_me\node_modules\rc
tui\themes\pure\tables.less Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (F:\react\react+redux教程\todos-with-undo_me\node_modules
\webpack\node_modules\acorn\dist\acorn.js:923:13)
    at Parser.pp.getTokenFromCode (F:\react\react+redux教程\todos-with-undo_me\n
ode_modules\webpack\node_modules\acorn\dist\acorn.js:2831:8)
    at Parser.pp.readToken (F:\react\react+redux教程\todos-with-undo_me\node_mod
ules\webpack\node_modules\acorn\dist\acorn.js:2526:15)
    at Parser.pp.nextToken (F:\react\react+redux教程\todos-with-undo_me\node_mod
ules\webpack\node_modules\acorn\dist\acorn.js:2518:71)
    at Parser.parse (F:\react\react+redux教程\todos-with-undo_me\node_modules\we
bpack\node_modules\acorn\dist\acorn.js:1631:10)
    at Object.parse (F:\react\react+redux教程\todos-with-undo_me\node_modules\we
bpack\node_modules\acorn\dist\acorn.js:885:44)
    at Parser.parse (F:\react\react+redux教程\todos-with-undo_me\node_modules\we
bpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (F:\react\react+redux教程\todos-with-undo_m
e\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (F:\react\react+redux教程\todos-with-undo
_me\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:
10)
    at nextLoader (F:\react\react+redux教程\todos-with-undo_me\node_modules\webp
ack\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
 @ ./~/rctui/themes ^\.\/.*\.less$

WARNING in ./~/rctui/themes/pure/tip.less
Module parse failed: F:\react\react+redux教程\todos-with-undo_me\node_modules\rc
tui\themes\pure\tip.less Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (F:\react\react+redux教程\todos-with-undo_me\node_modules
\webpack\node_modules\acorn\dist\acorn.js:923:13)
    at Parser.pp.unexpected (F:\react\react+redux教程\todos-with-undo_me\node_mo
dules\webpack\node_modules\acorn\dist\acorn.js:1490:8)
    at Parser.pp.parseExprAtom (F:\react\react+redux教程\todos-with-undo_me\node
_modules\webpack\node_modules\acorn\dist\acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (F:\react\react+redux教程\todos-with-undo_m
e\node_modules\webpack\node_modules\acorn\dist\acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (F:\react\react+redux教程\todos-with-undo_me\no
de_modules\webpack\node_modules\acorn\dist\acorn.js:207:17)
    at Parser.pp.parseExprOps (F:\react\react+redux教程\todos-with-undo_me\node_
modules\webpack\node_modules\acorn\dist\acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (F:\react\react+redux教程\todos-with-undo
_me\node_modules\webpack\node_modules\acorn\dist\acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (F:\react\react+redux教程\todos-with-undo_me\n
ode_modules\webpack\node_modules\acorn\dist\acorn.js:112:19)
    at Parser.pp.parseExpression (F:\react\react+redux教程\todos-with-undo_me\no
de_modules\webpack\node_modules\acorn\dist\acorn.js:88:19)
    at Parser.pp.parseStatement (F:\react\react+redux教程\todos-with-undo_me\nod
e_modules\webpack\node_modules\acorn\dist\acorn.js:1771:23)
 @ ./~/rctui/themes ^\.\/.*\.less$

WARNING in ./~/rctui/themes/pure/tree.less
Module parse failed: F:\react\react+redux教程\todos-with-undo_me\node_modules\rc
tui\themes\pure\tree.less Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (F:\react\react+redux教程\todos-with-undo_me\node_modules
\webpack\node_modules\acorn\dist\acorn.js:923:13)
    at Parser.pp.unexpected (F:\react\react+redux教程\todos-with-undo_me\node_mo
dules\webpack\node_modules\acorn\dist\acorn.js:1490:8)
    at Parser.pp.parseExprAtom (F:\react\react+redux教程\todos-with-undo_me\node
_modules\webpack\node_modules\acorn\dist\acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (F:\react\react+redux教程\todos-with-undo_m
e\node_modules\webpack\node_modules\acorn\dist\acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (F:\react\react+redux教程\todos-with-undo_me\no
de_modules\webpack\node_modules\acorn\dist\acorn.js:207:17)
    at Parser.pp.parseExprOps (F:\react\react+redux教程\todos-with-undo_me\node_
modules\webpack\node_modules\acorn\dist\acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (F:\react\react+redux教程\todos-with-undo
_me\node_modules\webpack\node_modules\acorn\dist\acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (F:\react\react+redux教程\todos-with-undo_me\n
ode_modules\webpack\node_modules\acorn\dist\acorn.js:112:19)
    at Parser.pp.parseExpression (F:\react\react+redux教程\todos-with-undo_me\no
de_modules\webpack\node_modules\acorn\dist\acorn.js:88:19)
    at Parser.pp.parseStatement (F:\react\react+redux教程\todos-with-undo_me\nod
e_modules\webpack\node_modules\acorn\dist\acorn.js:1771:23)
 @ ./~/rctui/themes ^\.\/.*\.less$

ERROR in ./~/rctui/index.js
Module not found: Error: Cannot resolve module 'refetch' in F:\react\react+redux
教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/index.js 52:32-50

ERROR in ./~/rctui/CheckboxGroup.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/CheckboxGroup.js 9:18-39

ERROR in ./~/rctui/Checkbox.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Checkbox.js 7:18-39

ERROR in ./~/rctui/Textarea.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Textarea.js 9:18-39

ERROR in ./~/rctui/Icon.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Icon.js 7:18-39

ERROR in ./~/rctui/Input.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Input.js 9:18-39

ERROR in ./~/rctui/RadioGroup.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/RadioGroup.js 9:18-39

ERROR in ./~/rctui/Button.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Button.js 7:18-39

ERROR in ./~/rctui/Rating.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Rating.js 7:18-39

ERROR in ./~/rctui/Select.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Select.js 9:18-39

ERROR in ./~/rctui/Switch.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Switch.js 7:18-39

ERROR in ./~/rctui/Upload.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Upload.js 3:18-39

ERROR in ./~/rctui/FormControl.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/FormControl.js 7:18-39

ERROR in ./~/rctui/Form.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Form.js 11:18-39

ERROR in ./~/rctui/Grid.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Grid.js 7:18-39

ERROR in ./~/rctui/Pagination.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Pagination.js 7:18-39

ERROR in ./~/rctui/Table.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Table.js 9:18-39

ERROR in ./~/rctui/Filter.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Filter.js 9:18-39

ERROR in ./~/rctui/Modal.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Modal.js 5:18-39

ERROR in ./~/rctui/higherOrders/Fetch.js
Module not found: Error: Cannot resolve module 'refetch' in F:\react\react+redux
教程\todos-with-undo_me\node_modules\rctui\higherOrders
 @ ./~/rctui/higherOrders/Fetch.js 14:15-33

ERROR in ./~/rctui/Message.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Message.js 13:18-39

ERROR in ./~/rctui/Modal.js
Module not found: Error: Cannot resolve module 'pubsub-js' in F:\react\react+red
ux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Modal.js 17:16-36

ERROR in ./~/rctui/Message.js
Module not found: Error: Cannot resolve module 'pubsub-js' in F:\react\react+red
ux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Message.js 21:16-36

ERROR in ./~/rctui/higherOrders/FormItem.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui\higherOrders
 @ ./~/rctui/higherOrders/FormItem.js 14:18-39

ERROR in ./~/rctui/TableHeader.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/TableHeader.js 7:18-39

ERROR in ./~/rctui/Datepicker/Datetime.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui\Datepicker
 @ ./~/rctui/Datepicker/Datetime.js 7:18-39

ERROR in ./~/rctui/Overlay.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui
 @ ./~/rctui/Overlay.js 7:18-39

ERROR in ./~/rctui/Tree/Tree.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui\Tree
 @ ./~/rctui/Tree/Tree.js 11:18-39

ERROR in ./~/rctui/Datepicker/Clock.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui\Datepicker
 @ ./~/rctui/Datepicker/Clock.js 9:18-39

ERROR in ./~/rctui/Tree/Item.js
Module not found: Error: Cannot resolve module 'classnames' in F:\react\react+re
dux教程\todos-with-undo_me\node_modules\rctui\Tree
 @ ./~/rctui/Tree/Item.js 5:18-39

**Comment by haoliangwu** [comment]
首先你需要先安装classnames, refetch, pubsub-js这几个module。
``
npm i classnames --save-dev
``
其次你可能需要配置less-loader来处理.less文件，注意，这个是处理node_modules里面包含的.less文件。

这个cli我只用过一次，我记得是好用的。

不过你既然是todo的项目的话，其实你也可以试试用其他的项目脚手架工具，我最近一直再用[nwb](https://github.com/insin/nwb)。

我有一个[玩具](https://github.com/haoliangwu/eat-what)项目就是用nwb+react-ui搭建的，除了默认的配置，只需要再安装nwb-less nwb-sass插件还有配置一下postCSS的插件即可，看[这里](https://github.com/haoliangwu/eat-what/blob/master/nwb.config.dev.js)，很方便。

同时，最近fb还自己做了一个，(create-react-app)[https://github.com/facebookincubator/create-react-app]，基本的配置不支持css预处理器，不过可以通过eject来实现高级配置，也很方便。

希望对你有帮助~

**Comment by Lobos** [comment]
这个错误是缺 'classnames' 和 'less-loader'，你的npm版本是多少？

**Comment by kakusang** [comment]
2.15.8

**Comment by kakusang** [comment]
@haoliangwu 好的，谢谢你的帮助

**Comment by Lobos** [comment]
@kakusang 那个cli是要npm > 3的，2下面有点问题。
