### ISSUE TITLE
Modal在firefox的兼容性问题

### ISSUE THREAD

**Issue by Cicy-caicai** [Lobos/react-ui#63]
在Firefox中，Modal中button即使设置为“submit”仍不能触发提交表单的行为，主要是event.initEvent缺少2个参数，如event.initEvent("submit",true,true).

另外“This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web apps using it may break at any time.” 希望替换成比较合适的方法

**Comment by haoliangwu** [comment]
@Lobos 
文档有这个问题，不过dev没这个问题。initEvent确实deprecated了，改成
``new Event('submit', {'bubbles': true, 'cancelable': true}``？

**Comment by Lobos** [comment]
嗯，确实有这个问题，发了0.6.7，改成优先使用CustomEvent了
