### ISSUE TITLE
用npm下载下来的包，是ES6 源码经过编译过的吗？好像有个问题

### ISSUE THREAD

**Issue by Miao5995** [Lobos/react-ui#64]
对于我用npm install下载下来的包来说，Tree组件里的item.js，多处地方出现了React.createElement，如第210行，而其实require的是 _react，这个是编译的问题吗？

**Comment by Lobos** [comment]
嗯，我发布之前用babel把es6转成es5了，打算降低一些使用门槛（好像并没有什么用😃），不用看那个代码。

**Comment by Miao5995** [comment]
恩恩，明白了，感谢回复~

不过我感觉babel转的有点问题啊。。。

item.js 会报错，136行报React not defined

136行：
`   return React.createElement(
      'a',
      { className: className, onClick: this.check },
      React.createElement('i', { className: 'tree-icon ' + check })
    );`

前面第3行有一个：`var _react = require('react'); `

我把item.js 里面的React都改成_react，组件就能用了。。。

不知道babel为什么会转成这样呢。。。

**Comment by Lobos** [comment]
你是把React也打包了么？webpack配置一下，react.js单独引用吧
```
 externals: {'react': 'React', 'react-dom': 'ReactDOM'}
```

**Comment by Miao5995** [comment]
啊哈，明白了，感谢~

**Comment by Miao5995** [comment]
嗯，确实之前没有加externals，

**Comment by Miao5995** [comment]
但是加上了externals: {'react': 'React', 'react-dom': 'ReactDOM'}，还是报React not defined

**Comment by Lobos** [comment]
我发了一个新版，没有转es5的，如果还是React not defined，试一下这个https://www.npmjs.com/package/babel-plugin-react-require
