### ISSUE TITLE
分页组件mini，不能设置index

### ISSUE THREAD

**Issue by Miao5995** [Lobos/react-ui#65]
http://lobos.github.io/react-ui/0.6/#/pagination

pagination，勾选mini之后，改变index值，组件展现不变

![image](https://cloud.githubusercontent.com/assets/13131073/18118809/b4fe0eb2-6f89-11e6-8e5c-457ab2c16a9e.png)

**Comment by Lobos** [comment]
为了防止每次输入都会发起分页请求，这里放了一个form，回车确认后才会触发。
这个后面再想想是否有更好的交互。

**Comment by Lobos** [comment]
0.7 改进了这个问题。
