### ISSUE TITLE
编译问题请教

### ISSUE THREAD

**Issue by becaLG** [Lobos/react-ui#67]
你好，感觉这个UI不错 打算应用，但是，编译ES6的时候遇到问题，编译使用的是glup+babel6,用babel编译的ES6和jsx，但是，在编译的时候报错，如图<img src="http://7xjtzg.com1.z0.glb.clouddn.com/uploads/default/original/2X/3/3723ed63dd586fc3a8c8e0b7f1925803f38145de.png" width="690" height="447">
代码中错误指向<img src="http://7xjtzg.com1.z0.glb.clouddn.com/uploads/default/optimized/2X/6/6099c75a13de2883878f62d459b79be8552845c6_1_481x500.png" width="481" height="500">let { label, layout, items, children, ...otherProps} = props;都是类似这样的赋值报错，作者知道这个该怎么解决么？查了很久，都没找到解决办法。

**Comment by Lobos** [comment]
babel 里面加上 transform-object-rest-spread
···
npm install babel-plugin-transform-object-rest-spread
···
···
{
  "presets": ["react", "es2015-loose"]
  "plugins": ["transform-object-rest-spread"]
}
···

**Comment by becaLG** [comment]
多谢！问题解决！
