### ISSUE TITLE
在table中使用pagination组件，pagination中传入的参数total不能正常获取

### ISSUE THREAD

**Issue by sallimy** [Lobos/react-ui#71]
大神们，我参考demo例子使用Table组件，添加Pagination组件，如下：
```
<Table 
      ...
      data={data}
      pagination={<Pagination size={10} total={30}/>} >
    </Table>
```
Pagination组件中显示的页数一直为1。断点调试源码，Pagination组件的total值会被Table组件内部定义的total给覆盖，导致在Pagination组件中获取的total值为Table的单页数据长度，而不是Pagination中传入的total总数据长度。

我是npm install 安装`"rctui": "^0.6.8"`的。

**Comment by Lobos** [comment]
那个内部的分页是给一次请求大量数据，在前端分页用的。
如果是服务端分页的数据，就不要用内置的Pagenation了，在Table外部分页就好了。

**Comment by sallimy** [comment]
原来是这样，放table外就解决了，谢谢@Lobos啊！

**Comment by Lobos** [comment]
😊
