### ISSUE TITLE
关于Form组件重置的问题

### ISSUE THREAD

**Issue by sallimy** [Lobos/react-ui#72]
请教下，现Form组件不支持表单重置，有什么方法可以在原有Form组件的基础上实现表单的reset啊？

**Comment by Lobos** [comment]
0.6的话，应该可以传一个空 {} 的 data 给 Form

**Comment by haoliangwu** [comment]
@sallimy 直接reset data不就可以了吗，传个空的data给form。

**Comment by sallimy** [comment]
嗯嗯，是的，刚发现，哈哈，谢谢 @Lobos @haoliangwu 啊！
