### ISSUE TITLE
Datepicker in english?

### ISSUE THREAD

**Issue by raptoria** [Lobos/react-ui#76]
Is there an option to set the language on the datepicker? I can read Chinese but I don't think my team will appreciate it, since they cannot.

This UI framework is gorgeous!

**Comment by haoliangwu** [comment]
Sorry for the delay. 

To get ``en`` locale, you can use ``setLocation`` Fn to make it. If you know well Chinese, refer to [here](http://lobos.github.io/react-ui/0.6/#/lang) for more information.

**Comment by Lobos** [comment]
Yes, you can use setLocation fn.
```
import { setLocation } from 'rctui/lang'
setLocation('en')
```

I release a new version 0.7, you can use config to set language
```
import config from 'rctui/config'
config.location = 'en|zh-cn'
```

**Comment by raptoria** [comment]
cool thanks! Do you have a documentation in English? Having trouble convincing my team to use it otherwise... I think with an English doc your framework would really catch fire.

**Comment by Lobos** [comment]
In 0.7, I add a button in the top right conner of the document to switch the document language.
But my english is not very good. So there may be some mistake, if it makes you confused, let me know...

**Comment by anoyi09** [comment]
blueimp-md5 is not find?Why?

**Comment by anoyi09** [comment]
blueimp-md5.js is not find?Why?

**Comment by Lobos** [comment]
try
```
npm install blueimp-md5 --save
```

**Comment by raptoria** [comment]
I don't see the button that switches the document language :/

**Comment by Lobos** [comment]
It's a link button.
![language button](https://cloud.githubusercontent.com/assets/101764/20910532/0a0e1352-bb9d-11e6-92ad-c651cb42037a.png)

**Comment by raptoria** [comment]
oh I see. thanks!
