### ISSUE TITLE
你是玩我们的吧

### ISSUE THREAD

**Issue by justnode** [Lobos/react-ui#80]
我想问问 你开源这个  npm 安装依赖后，连个demo都跑不起来，你是猴子派来的逗比吗   安装各种报错，你是把github当做托管的工具还是开源？

**Comment by Lobos** [comment]
这个项目已经1000多star，阿里、百度、网易都有人在用，如果你觉得你配置不起来，去用别的就可以了，谢谢。

**Comment by wdd119** [comment]
哈哈
