### ISSUE TITLE
SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by LuanLouis** [Lobos/react-ui#83]
作者您好，我尝试使用你们的组件，但是报了错误:`SyntaxError: Unexpected token`
具体情况如下：
`Error in ./~/rctui/Button.js
Module parse failed: G:\sources\auth-center\auth-center-react-web\node_modules\rctui\Button.js Unexpected token (31:56)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (31:56)
 @ ./src/App.js 20:14-37`
相对应的行数相应的代码是：
`let { children, status, size, grid, tag, className, ...others } = this.props`
好像是识别不了`...others`。
我是react新手入门，请作者多多指教。
![qq 20170108015044](https://cloud.githubusercontent.com/assets/7589877/21743834/70d5136c-d545-11e6-999d-42061395f04a.png)
![qq 20170108015512](https://cloud.githubusercontent.com/assets/7589877/21743840/83b92658-d545-11e6-91d8-5868a4fc8e54.png)

**Comment by Lobos** [comment]
需要安装babel-transform-object-rest-spread 这个插件，并且配置一下
```
{
        test: /\.jsx?$/,
        loader: 'babel',
        query: {
          presets: ['react', 'es2015'],
          plugins: ['transform-object-rest-spread', 'react-require']
        }
      }
```
