### ISSUE TITLE
Popover组件嵌套react-router报错

### ISSUE THREAD

**Issue by greyj2009** [Lobos/react-ui#84]
`<Popover position="right" trigger="click"><div><img src={require('../static/img/icon-info-mouse.png')} alt="" /><p>消息</p></div><div><Link to="/messageList" title="messageList"><p>消息列表</p></Link><Link to="/messageTemplate" title="messageTemplate"><p>消息模板</p></Link></div></Popover>`
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
新手求教，谢谢

**Comment by Lobos** [comment]
首先，开发的时候加载react-with-addons.js未压缩的版本代替react-min.js，看下详细的问题。
<img src={require('../static/img/icon-info-mouse.png')} alt="" /> 这个感觉是有问题的
