### ISSUE TITLE
npm run dev报app.js:1 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by fhqdgv** [Lobos/react-ui#86]
是不是这里引起的
app.get('/*', function (req, res) {
  res.sendFile(path.join(__dirname, 'docs/src/index.html'))
})
![1](https://cloud.githubusercontent.com/assets/6103043/22280047/59b1401c-e309-11e6-82fd-939cc1d1e237.png)

**Comment by Lobos** [comment]
demo里面的那个示例是要先配置webpack-dev-middleware的
```
app.use(require('webpack-dev-middleware')(compiler, {
  noInfo: true,
  publicPath: '/'
}));
```
