### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by luojunbin** [Lobos/react-ui#88]
Please publish the compiled code to npm, Not everyone will include the node_modules at compile time;

**Comment by gcperrin** [comment]
Big plus one here, realistically unusable otherwise.

**Comment by Lobos** [comment]
Just release 0.7.12, add the compiled file
```
import { Form } from 'rctui/dist'
```
Or use unpkg cdn file
```
<script src="https://unpkg.com/rctui/dist/index.js"></script>
```
