### ISSUE TITLE
引用了 rctui 出错？？

### ISSUE THREAD

**Issue by DuAChao** [Lobos/react-ui#89]
引用了 rctui 的Alert 组件正常，但是引用其他都报错-显示 React is not defined，不知什么原因？求解答啊

**Comment by zongwei007** [comment]
是不是没有引入 [babel-plugin-react-require](https://www.npmjs.com/package/babel-plugin-react-require) 插件？

**Comment by Lobos** [comment]
应该是没有配置 babel-plugin-react-require
