### ISSUE TITLE
ES6 support required

### ISSUE THREAD

**Issue by Duan112358** [Lobos/react-ui#9]
Hi, webpack compile error occur
<img width="779" alt="screen shot 2015-09-23 at 11 32 24" src="https://cloud.githubusercontent.com/assets/1957818/10037340/5634f09a-61e7-11e5-9fe7-6af27e255eb3.png">
 what i have done
``` jsx
import { Pagination, Table } from 'rctui'
```
and webpack loader config
``` jsx
{test: /\.jsx?$/,
loaders: ['react-hot', 'babel?stage=0'],
exclude: /node_modules/,
include: __dirname}
```

**Comment by Duan112358** [comment]
it's not 'use strict''s  problem. I extract the source code to my own project, and used as usual, no problem

so, may be just the npm package's issues

**Comment by Lobos** [comment]
试试 'babel-loader'
```
loaders: ['react-hot', 'babel-loader?stage=0']
```

**Comment by Duan112358** [comment]
@Lobos it works. thks
