### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by LiuC520** [Lobos/react-ui#92]
您好，我配置了babel，还是报错，就引入了一个：import {Button} from 'rctui';
我的babel，配置是在package.json中配置的
"babel": {
     "presets": [
       "es2015",
       "react",
       "stage-3"
     ],
    "plugins": [
      "transform-object-rest-spread",
      "react-require",
      "transform-es2015-modules-commonjs"
    ]
  }
还是报错，
在。babelrc里面也配置，也报这样的错
报错说是index.js：1，打开后是：import './styles/reset.scss'，这个报错，我就蒙了

**Comment by Lobos** [comment]
webpack 的sass有没有配置

**Comment by LiuC520** [comment]
这个没有哦，怎么配置的，我没有webpack，直接新建的react项目，然后直接npm install --save rctui的，然后新建了一个.babelrc文件，然后里面放了下面的代码：
{
  "presets": ["react", "es2015"],
  "plugins": [
    ["transform-es2015-classes", {loose: true}],
    "transform-object-rest-spread",
    "react-require"
  ]
}
这个webpack也要配置么？还不知道如何配置呢

**Comment by Lobos** [comment]
建一个空项目，执行
```
npm install rctui
node node_modules/rctui/cli/init.js all
```
会安装好所有依赖，生成webpack.config.js，和一个demo

**Comment by LiuC520** [comment]
ok，我试下，谢谢喽
