### ISSUE TITLE
能加一个card的容器吗

### ISSUE THREAD

**Issue by imcloud** [Lobos/react-ui#93]
根据屏幕宽度一行自动放置1～n个card

ps：card怎么加hover_(:_」∠)_，初上手的菜鸟

**Comment by Lobos** [comment]
没有太明白你的意思，card是定宽的还是百分比的？定宽的，设置 display:inline-block 就好了，不需要单独做组件。hover的话，直接用css伪类  :hover 就可以了。

**Comment by imcloud** [comment]
_(:_」∠)_  噗 谢谢了

是因为看到了其他的一个库提供了card的瀑布流框架
类似于
<card_frame>
<card />
.
.
<card />
</card_frame>
这个感觉，中间放多少个都行，布局会自动处理。但是更喜欢你的这个消息提示的功能，所以还是决定用你的啦
