### ISSUE TITLE
webpack打包报错

### ISSUE THREAD

**Issue by byself** [Lobos/react-ui#95]
`ERROR in ./~/rctui/Button.js 

Module parse failed: /Users/wangzili/WebstormProjects/cosmetic_fe/node_modules/rctui/Button.js Unexpected token (31:56)
You may need an appropriate loader to handle this file type.
|
|   render () {
|     let { children, status, size, grid, tag, className, ...others } = this.props
|
|     className = classnames(

 @ ./~/rctui/index.js 3:0-44
 @ ./cosmetic/src/modules/merchant/merchant.jsx
 @ ./cosmetic/src/modules/home/home.jsx
 @ ./cosmetic/src/routers/router.js`

**Comment by byself** [comment]
只要是有classnames的文件都报错

**Comment by byself** [comment]
webpack: 2.4.1
node: 7.6.0
npm: 4.1.2

**Comment by byself** [comment]
只要是有classnames的文件都报错.
配置：
webpack: 2.4.1
node: 7.6.0
npm: 4.1.2

**Comment by Lobos** [comment]
看下classnames这个模块有没有安装，可以参考这个项目https://github.com/Lobos/react-example
