### ISSUE TITLE
组件创建后没有样式，可能是我使用有问题，或者缺少插件？

### ISSUE THREAD

**Issue by baijunjie** [Lobos/react-ui#98]
根据文档的描述应该是这么写的：
```js
import { Input } from 'rctui'

render() {
    return (
          <Input grid={1 / 4} placeholder="text" />
    )
}
```
查看生成的DOM元素，发现没有 `_input-input` 类，并且其他组件都有类似情况
```html
<input type="text" placeholder="text" class="s_ab3b313b s_b023e9b9 s_44ecee11 " value="">
```
我看到组件的 className 似乎是使用一个叫 `classnames` 的插件生成的，我也安装了，并且代码编译都ok，并没有报错。

还有一个问题就是，如果我仅仅引入一个 Input 组件，但是网页中却生成了很多 <style> 标签，貌似是所有组件的样式都被创建了，不知道是不是和 sass-loader 的配置有关？

目前是页面中加载了所有样式 <style>，但是生成的组件 DOM 没有应有的类，导致全部没有样式，求老司机带路！

**Comment by Lobos** [comment]
css-loader 需要配置一下localIdentName，这个是webpack2的配置
```
{
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[name]-[local]',
            },
          }
```

**Comment by baijunjie** [comment]
@Lobos 加了，但是没有什么变化，我的脚手架是用 vue-cli 改造的，所以配置代码可能和一般配置不一样
加了 `modules: true` 后会报错，去掉就编译通过了，但是没有什么变化。

![cd0bfe3e-ba43-4abf-958d-664162b8347f](https://user-images.githubusercontent.com/7956480/27670195-ee40ebfa-5cbd-11e7-9aec-724edd5d40f6.png)

另外这个配置能帮助解决组件DOM没有生成对应class的问题吗？

**Comment by baijunjie** [comment]
我看到文档中的 input 的 class 中有 `_input-input` 类，但是我加在我创建的 input 上也没有效果，好像是动态创建的？

我看到 sass 文件是生成了一个 `.input` 的类，我加上以后就有样式了，我不是很明白，这个类必须要手动加吗？组件不会自动生成？

手动加的话 input 好办，有些组件不可能每个元素都能手动加上。囧

**Comment by baijunjie** [comment]
这是通过 sass-loader 加载进来的样式
![968718ca-c8c9-4e54-98dd-0ce574a461d5](https://user-images.githubusercontent.com/7956480/27670729-6bf44346-5cc1-11e7-9e99-7b56bac470df.png)

**Comment by baijunjie** [comment]
目前主要用到表格和分页组件，分页组件我无法给他手动添加所有的类，只能添加最外层的 `.pagination`，子项的类是无能为力了，求救

**Comment by Lobos** [comment]
完整的配置是这样的
```
{
        test: /\.scss$/,
        use: [
          { loader: 'style-loader' },

          {
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[name]-[local]',
            },
          },

          {
            loader: 'postcss-loader',
            options: {
              plugins() {
                return [
                  autoprefixer,
                ]
              },
            },
          },

          {
            loader: 'sass-loader',
          },
        ],
      },
```

**Comment by Lobos** [comment]
要覆盖默认的样式的话，在自己的项目下面建一个相同名称的文件，比如_pagination.scss，按原来的结构写要覆盖的样式，然后import这个文件就行了
```
.pagination {
  display: inline-block;
  padding-left: 0;

  li {
    display: inline-block;
    vertical-align: middle;
   ...
```

**Comment by baijunjie** [comment]
好的，样式问题好解决。

现在是组件生成的 dom 没有一并生成对应的 className，导致table和pagination都没有样式，我想确认一下，是这样设计的吗？还是我使用姿势不对？

**Comment by baijunjie** [comment]
文档中并没有提到要手动添加className
```jsx
<Pagination
  page={this.state.page}
  size={this.state.size}
  total={this.state.total}
  range={this.state.range}
  mini={this.state.mini}
  large={this.state.lms === 'large'}
  small={this.state.lms === 'small'}
  onChange={(page) => this.setState({ page })}
/>
```
我也是按照文档中的代码写的，可出出来的效果就....
```html
<div>
    <ul class="">
        <li class="">
            <a href="javascript:;">
                <!-- react-text: 97 -->&nbsp;
                <!-- /react-text -->
                <svg width="48" height="48" viewBox="0 0 48 48">
                    <g transform="translate(10,14) scale(-1,1) translate(-10,-14) translate(-14,-10) ">
                        <path d="m3.93096,19.5l-2.43096,2.6319l12.03714,11.8681l-12.03714,12.03797l2.43096,2.46203l14.56904,-14.5l-14.56904,-14.5z" fill="#999"></path>
                    </g>
                </svg>
            </a>
        </li>
        <li class=""><a href="javascript:;">1</a></li>
        <li class=""><span>2</span></li>
        <li class="">
            <a href="javascript:;">
                <!-- react-text: 107 -->&nbsp;
                <!-- /react-text -->
                <svg width="48" height="48" viewBox="0 0 48 48">
                    <path fill="#999" d="m17.93096,9.5l-2.43096,2.6319l12.03714,11.8681l-12.03714,12.03797l2.43096,2.46203l14.56904,-14.5l-14.56904,-14.5z"></path>
                </svg>
            </a>
        </li>
    </ul>
</div>
```
<img width="75" alt="fca42d09-62c9-4432-8c98-a07db6e28760" src="https://user-images.githubusercontent.com/7956480/27678199-ed3522ac-5ce6-11e7-97bf-a7727f5a36fc.png">
最主要的是分页中的前一页和下一页按钮，我无法手动添加className。T_T

**Comment by Lobos** [comment]
应该还是webpack配置的问题，可以参考这个项目 https://github.com/Lobos/react-example

**Comment by baijunjie** [comment]
好纠结，又报错了。
之前我的 node 是 7.6 报 async 函数错误。然后根据 readme 提示升级了node 到 8.0，server 是启动了。但是 console 中又报错了，用一个 UI 组件怎么这么难 T_T。
![5f635257-1130-4f7b-8418-0fdc72ea1a6a](https://user-images.githubusercontent.com/7956480/27716721-ec11ae40-5d72-11e7-809c-0c9d3c7fbd96.png)
报错意思貌似是代码运行环境被绑定在 node7.X ??

**Comment by baijunjie** [comment]
demo 跑起来了，发现 react-ui 居然对 css-loader 的 Module 功能是强依赖？
```js
           options: {
              modules: true,
              localIdentName: '[name]-[local]',
            }
```
如果删除这个选项，就会出现和我一样的问题。
很纠结，首先，在我的框架里添加这个设置会报错。其次，我并不需求为样式创建单独的命名空间。我只希望能正常引入 bootstrap 样式就好，className 保持原样就ok。

**Comment by vipcxj** [comment]
你可以用include属性来限制modules的使用范围

**Comment by baijunjie** [comment]
由于项目中使用的是 bootstrap，甲方不愿意更换其他UI框架。刚好看到 Lobos 的 react-ui 是基于 bootstrap，就想借用这个框架节省以下工作量，没想到卡了三天 :joy:。

我提几点建议哈。
1）希望能尽量减少对 webpack 插件的强依赖（比如：所有文件加入`import React`，而不是使用`babel-plugin-react-require`），如果必须依赖，希望能在文档中指明。毕竟每个人搭建的开发框架不同。
2）建议不要把 bootstrap 的 sass 源文件直接放在 react-ui 里。
    首先，大部分人对修改 bootstrap 样式是没有需求的
    其次，在开发环境下，每次修改都会重新去编译所有 sass 文件，很不科学。
    再次，这又导致了 react-ui 必须依赖 sass-loader 和 node-sass
3) 可以将样式源文件的修改编译功能交给  react-ui-theme 模块来完成。然后 react-ui 增加一个修改className 前缀的方法。

看了 react-ui 的文档，感觉很不错，Lobos 一己之力构建起来真的很赞！希望 react-ui 能降低一些使用难度，让开发者更容易上手。

**Comment by Lobos** [comment]
1）import React 的问题，只有在把React打包在项目里才会出现，建议是不要把React打包在项目里。
2）react-ui用了bootstrap的机制，但是所有的组件结构和bootstrap是完全不同的，所以不能直接用bootstrap的组件。开发下编译sass的时间基本可以忽略不计，可以比较灵活的覆盖样式。
3）修改前缀， css-module 就可以实现，在SPA的应用中，css-module完全避免了className冲突的问题。
